In [1]:
#import OpenCV module
import cv2
#import os module for reading training data directories and paths
import os
#import numpy to convert python lists to numpy arrays as 
#it is needed by OpenCV face recognizers
import numpy as np

In [2]:
def name_map(x):
    if x=='sachin':
        return 0
    if x=='obama':
        return 1
    if x == 'messi':
        return 2

In [3]:
def get_name(x):
    if x==0:
        return 'sachin'
    if x==1:
        return 'obama'
    if x == 2:
        return 'messi'

In [4]:
#there is no label 0 in our training data so subject name for index/label 0 is empty
#subjects = ["sachin", "obama","messi"]

#function to detect face using OpenCV
def detect_face(img):
    #convert the test image to gray image as opencv face detector expects gray images
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #load OpenCV face detector, I am using haarcascade_frontalface_default
    
    face_cascade = cv2.CascadeClassifier('data/haarcascade_frontalface_default.xml')
    #let's detect multiscale (some images may be closer to camera than others) images
    #result is a list of faces
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.2, minNeighbors=5);
    
    #if no faces are detected then return original img
    if (len(faces) == 0):
        return None, None
    
    #under the assumption that there will be only one face,
    #extract the face area
    (x, y, h, w) = faces[0]
    
    #return only the face part of the image
    return gray[y:y+h, x:x+w], faces[0]

In [5]:
def prepare_training_data(data_folder_path):
    
    #------STEP-1--------
    #get the directories (one directory for each subject) in data folder
    dirs = os.listdir(data_folder_path)
    
    #list to hold all subject faces
    faces = []
    #list to hold labels for all subjects
    labels = []
    
    #let's go through each directory and read images within it
    for dir_name in dirs:
        
            
        #------STEP-2--------
        #extract label number of subject from dir_name
        label = dir_name
        
        #build path of directory containin images for current subject subject
        #sample subject_dir_path = "data/DB/sachin"
        subject_dir_path = data_folder_path + "/" + dir_name
        
        #get the images names that are inside the given subject directory
        subject_images_names = os.listdir(subject_dir_path)
        
        #------STEP-3--------
        #go through each image name, read image, 
        #detect face and add face to list of faces
        for image_name in subject_images_names:
            
            #ignore system files like .DS_Store
            if image_name.startswith("."):
                continue;
            
            #build image path
            #sample image path = training-data/s1/1.pgm
            image_path = subject_dir_path + "/" + image_name

            #read image
            image = cv2.imread(image_path)
            print(image) #you will get a numpy array
            #display an image window to show the image 
            cv2.imshow("Training on image...", image)
            cv2.waitKey(500)
            
            #detect face
            face, rect = detect_face(image)
            print(face) #if None there is no face, otherwise a numpy array
            
            
            #------STEP-4--------
            #for the purpose of this tutorial
            #we will ignore faces that are not detected
            if face is not None:
                #add face to list of faces
                faces.append(face)
                #add label for this face
                labels.append(name_map(label))
            
    cv2.destroyAllWindows()
    cv2.waitKey(1)
    cv2.destroyAllWindows()
    
    return faces, labels

In [6]:
print("Preparing data...")
faces, labels = prepare_training_data("data/DB")
print("Data prepared")

#print total faces and labels
print("Total faces: ", len(faces))
print("Total labels: ", len(labels))

Preparing data...
[[[211 234 250]
  [211 234 250]
  [211 234 250]
  ...
  [207 228 250]
  [207 228 250]
  [207 228 250]]

 [[211 234 250]
  [211 234 250]
  [211 234 250]
  ...
  [207 228 250]
  [207 228 250]
  [207 228 250]]

 [[211 234 250]
  [211 234 250]
  [211 234 250]
  ...
  [207 228 250]
  [207 228 250]
  [207 228 250]]

 ...

 [[127  78  68]
  [127  78  68]
  [127  78  68]
  ...
  [ 93  53  48]
  [ 94  54  49]
  [ 94  54  49]]

 [[127  78  68]
  [127  78  68]
  [127  78  68]
  ...
  [ 93  53  48]
  [ 94  54  49]
  [ 94  54  49]]

 [[126  77  67]
  [126  77  67]
  [126  77  67]
  ...
  [ 93  53  48]
  [ 94  54  49]
  [ 94  54  49]]]
[[244 243 243 ...  46  45  37]
 [244 243 243 ...  34  36  40]
 [244 243 243 ...  42  44  48]
 ...
 [214 202 199 ...  90 103  96]
 [201 188 186 ...  82  92  83]
 [199 184 185 ...  67  88  80]]
[[[ 40  41  51]
  [ 40  41  51]
  [ 40  41  51]
  ...
  [ 38  50  54]
  [ 36  51  54]
  [ 36  51  54]]

 [[ 40  41  51]
  [ 40  41  51]
  [ 40  41  51]
  ...
  

[[ 29  20  56 ... 122 124 124]
 [ 38  31  49 ... 122 124 124]
 [ 33  42  41 ... 122 124 124]
 ...
 [216 202 177 ...  95  98  97]
 [210 200 174 ... 199 145 134]
 [200 194 176 ... 240 245 238]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
[[247 234  70 ... 255 255 254]
 [251 198  14 ... 255 255 255]
 [254 127   9 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 

[[255 255 255 ... 246 253 253]
 [255 255 255 ... 244 255 255]
 [255 255 255 ... 249 254 252]
 ...
 [254 254 254 ...  19  16  15]
 [254 254 254 ...  17  13  11]
 [254 254 254 ...  14  10   8]]
[[[119 107 113]
  [114 102 108]
  [106  96 102]
  ...
  [182 192 210]
  [178 188 206]
  [165 177 195]]

 [[119 107 113]
  [114 102 108]
  [106  96 102]
  ...
  [197 209 227]
  [191 205 223]
  [180 194 212]]

 [[116 106 112]
  [113 103 109]
  [107  97 103]
  ...
  [196 211 230]
  [190 207 226]
  [179 196 215]]

 ...

 [[ 46  40  41]
  [ 46  40  41]
  [ 47  41  42]
  ...
  [ 41  31  37]
  [ 44  37  42]
  [ 48  41  46]]

 [[ 34  27  24]
  [ 34  27  24]
  [ 35  27  27]
  ...
  [ 30  16  20]
  [ 32  21  23]
  [ 35  24  26]]

 [[ 21  12   8]
  [ 21  12   8]
  [ 22  13  10]
  ...
  [ 21   7   9]
  [ 22  10  10]
  [ 24  12  12]]]
[[178 178 180 ... 164 164 163]
 [181 181 184 ... 168 167 167]
 [185 185 188 ... 173 172 172]
 ...
 [202 205 204 ... 202 202 201]
 [198 210 204 ... 204 203 202]
 [206 216 200 ... 

In [7]:
len(faces)

28

In [8]:
labels

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

# Face Recognition

In [9]:
cv2.__version__

'4.4.0'

In [10]:
face_recognizer = cv2.face.LBPHFaceRecognizer_create()

face_recognizer.train(faces, np.array(labels))   #X - faces and y - np.array(labels)

In [11]:
def draw_rectangle(img, rect):
    (x, y, w, h) = rect
    cv2.rectangle(img, (x, y), (x+w, y+h), (255, 255, 255), 2)

def draw_text(img, text, x, y):
    cv2.putText(img, text, (x, y), cv2.FONT_HERSHEY_PLAIN, 1.5, (255, 255, 255), 2)

In [12]:
def predict(test_img):
    #make a copy of the image as we don't want to chang original image
    img = test_img.copy()
    #detect face from the image
    face, rect = detect_face(img)

    #predict the image using our face recognizer 
    try:
        label= face_recognizer.predict(face)
        #get name of respective label returned by face recognizer
        #label_text = subjects[label[0]]
        label_text = get_name(label[0])
        #draw a rectangle around face detected
        draw_rectangle(img, rect)
        #draw name of predicted person
        draw_text(img, label_text, rect[0], rect[1]-5)
    except:
        pass
    
    return img

In [13]:
print("Predicting images...")

#load test images
test_img1 = cv2.imread("data/sachin.jpg")
test_img2 = cv2.imread("data/obama.jpg")
test_img3 = cv2.imread("data/messi1.jpg")

#perform a prediction
predicted_img1 = predict(test_img1)
predicted_img2 = predict(test_img2)
predicted_img3 = predict(test_img3)
print("Prediction complete")

#display both images
cv2.imshow("Image1", predicted_img1)
cv2.imshow("Image2", predicted_img2)
cv2.imshow("Image3", predicted_img3)
cv2.waitKey(0)
cv2.destroyAllWindows()

Predicting images...
Prediction complete


# Webcam

In [14]:
video_capture = cv2.VideoCapture(0) #To Read video 0 for webcam else you can give the video path

In [16]:
video_capture = cv2.VideoCapture(0)
while True:
    # Capture frame-by-frame
    ret, frame = video_capture.read()
    print(frame)
    print(type(frame))
    print(ret)

    predicted_img1 = predict(frame)
    # Display the resulting frame
    cv2.imshow('Video', predicted_img1)

    if cv2.waitKey(1) & 0xFF == 27:
        break
# When everything is done, release the capture
video_capture.release()
cv2.destroyAllWindows()

[[[210 200 188]
  [212 203 191]
  [216 207 201]
  ...
  [211 187 129]
  [210 184 127]
  [214 188 130]]

 [[210 200 190]
  [213 203 193]
  [216 208 205]
  ...
  [211 187 129]
  [210 184 127]
  [210 184 127]]

 [[212 201 194]
  [217 206 198]
  [218 210 213]
  ...
  [211 187 129]
  [214 188 130]
  [213 186 129]]

 ...

 [[ 62  42   0]
  [ 61  41   0]
  [ 59  38   0]
  ...
  [132 120  69]
  [134 120  75]
  [137 123  77]]

 [[ 65  45   3]
  [ 62  42   0]
  [ 61  40   0]
  ...
  [130 120  69]
  [134 121  73]
  [136 122  74]]

 [[ 61  43   1]
  [ 56  39   0]
  [ 55  34   0]
  ...
  [129 116  66]
  [130 116  68]
  [134 121  73]]]
<class 'numpy.ndarray'>
True
[[[207 203 197]
  [207 203 197]
  [209 207 207]
  ...
  [212 189 129]
  [208 187 122]
  [205 183 119]]

 [[205 200 194]
  [211 206 200]
  [211 210 212]
  ...
  [212 189 129]
  [208 186 124]
  [207 185 122]]

 [[204 201 197]
  [212 209 205]
  [213 215 217]
  ...
  [212 190 127]
  [211 188 126]
  [211 188 126]]

 ...

 [[ 86  70  36]
  [ 89 

[[[206 190 183]
  [213 197 190]
  [214 206 203]
  ...
  [204 178 114]
  [203 177 113]
  [208 181 117]]

 [[208 191 187]
  [214 197 193]
  [213 206 207]
  ...
  [207 181 115]
  [207 179 115]
  [209 180 116]]

 [[209 195 195]
  [213 200 200]
  [216 213 216]
  ...
  [205 180 113]
  [204 179 112]
  [200 174 108]]

 ...

 [[ 65  41   4]
  [ 59  35   0]
  [ 55  30   0]
  ...
  [147 132  62]
  [145 131  58]
  [144 130  57]]

 [[ 56  29   0]
  [ 55  28   0]
  [ 53  27   0]
  ...
  [146 131  61]
  [144 130  57]
  [141 127  54]]

 [[ 56  27   0]
  [ 55  25   0]
  [ 55  25   0]
  ...
  [146 131  61]
  [145 131  58]
  [143 128  56]]]
<class 'numpy.ndarray'>
True
[[[209 193 191]
  [212 197 195]
  [211 202 201]
  ...
  [209 181 122]
  [208 182 125]
  [206 179 122]]

 [[206 193 193]
  [211 198 197]
  [213 206 207]
  ...
  [209 182 120]
  [207 181 122]
  [204 179 119]]

 [[208 194 194]
  [215 201 201]
  [215 212 215]
  ...
  [208 181 119]
  [206 181 119]
  [204 180 118]]

 ...

 [[ 49  24   0]
  [ 52 

In [ ]:
#END